// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env['APIKEY'],
    appId: '1:460350402939:web:fc1e6320cb97a25d384dde',
    messagingSenderId: '460350402939',
    projectId: 'gosra-app',
    authDomain: 'gosra-app.firebaseapp.com',
    storageBucket: 'gosra-app.appspot.com',
    measurementId: 'G-LCTN7S59M0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['APIKEY'],
    appId: '1:460350402939:android:2d08894c73f4792b384dde',
    messagingSenderId: '460350402939',
    projectId: 'gosra-app',
    storageBucket: 'gosra-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['APIKEY'],
    appId: '1:460350402939:ios:7ed5bbc33894ec4f384dde',
    messagingSenderId: '460350402939',
    projectId: 'gosra-app',
    storageBucket: 'gosra-app.appspot.com',
    iosClientId:
        '460350402939-qim41udo3o2tnl167mepq6np8thr52r9.apps.googleusercontent.com',
    iosBundleId: 'com.example.gosraApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: dotenv.env['APIKEY'],
    appId: '1:460350402939:ios:7ed5bbc33894ec4f384dde',
    messagingSenderId: '460350402939',
    projectId: 'gosra-app',
    storageBucket: 'gosra-app.appspot.com',
    iosClientId:
        '460350402939-qim41udo3o2tnl167mepq6np8thr52r9.apps.googleusercontent.com',
    iosBundleId: 'com.example.gosraApp',
  );
}
